import React from "react"
import {
  Activity,
  Braces,
  Cloud,
  Code,
  Command,
  Container,
  Cpu,
  Database,
  GitBranch,
  Globe,
  HardDrive,
  Layout,
  Layers,
  Network,
  Server,
  Shield,
  Share2,
  Terminal,
  Workflow,
  Rocket,
  Lock,
  Zap,
} from "lucide-react"

export type TechCategoryId =
  "all" | "frontend" | "languages" | "backend" | "devops" | "tools"

export interface TechCategory {
  id: TechCategoryId
  label: string
  dotColor: string
  accentColor: string
}

export const TECH_CATEGORIES: TechCategory[] = [
  {
    id: "all",
    label: "All Stack",
    dotColor: "bg-foreground/70",
    accentColor: "neutral",
  },
  {
    id: "frontend",
    label: "Frontend",
    dotColor: "bg-sky-500",
    accentColor: "cyan",
  },
  {
    id: "languages",
    label: "Languages",
    dotColor: "bg-amber-500",
    accentColor: "pear",
  },
  {
    id: "backend",
    label: "Backend & Data",
    dotColor: "bg-emerald-500",
    accentColor: "mint",
  },
  {
    id: "devops",
    label: "Cloud & DevOps",
    dotColor: "bg-rose-500",
    accentColor: "coral",
  },
  {
    id: "tools",
    label: "Tools & Security",
    dotColor: "bg-purple-500",
    accentColor: "lavender",
  },
]

export type TechItem = {
  id: string
  label: string
  bg: string
  text: string
  icon: React.ReactNode
  category: "frontend" | "languages" | "backend" | "devops" | "tools"
  categoryLabel: string
  accentDot: string
  accentBorder: string
  accentGlow: string
  tag: string
}

export const TECH_STACK_DATA: TechItem[] = [
  // 1. Frontend (Sky Cyan)
  {
    id: "react",
    label: "React",
    category: "frontend",
    categoryLabel: "UI Library",
    bg: "bg-sky-500/10 dark:bg-sky-500/15",
    text: "text-sky-600 dark:text-sky-400",
    accentDot: "bg-sky-500",
    accentBorder: "hover:border-sky-500/50",
    accentGlow: "",
    tag: "Core",
    icon: <Code className="h-5 w-5" />,
  },
  {
    id: "nextjs",
    label: "Next.js",
    category: "frontend",
    categoryLabel: "Framework",
    bg: "bg-sky-500/10 dark:bg-sky-500/15",
    text: "text-sky-700 dark:text-sky-300",
    accentDot: "bg-sky-500",
    accentBorder: "hover:border-sky-500/50",
    accentGlow: "",
    tag: "Production",
    icon: <Rocket className="h-5 w-5" />,
  },
  {
    id: "tailwind",
    label: "Tailwind CSS",
    category: "frontend",
    categoryLabel: "Styling",
    bg: "bg-cyan-500/10 dark:bg-cyan-500/15",
    text: "text-cyan-600 dark:text-cyan-400",
    accentDot: "bg-cyan-500",
    accentBorder: "hover:border-cyan-500/50",
    accentGlow: "",
    tag: "Design",
    icon: <Layout className="h-5 w-5" />,
  },
  {
    id: "typescript",
    label: "TypeScript",
    category: "frontend",
    categoryLabel: "Typed JS",
    bg: "bg-sky-500/10 dark:bg-sky-500/15",
    text: "text-sky-600 dark:text-sky-400",
    accentDot: "bg-sky-500",
    accentBorder: "hover:border-sky-500/50",
    accentGlow: "",
    tag: "Type-Safe",
    icon: <Code className="h-5 w-5" />,
  },
  {
    id: "javascript",
    label: "JavaScript",
    category: "frontend",
    categoryLabel: "Web Core",
    bg: "bg-amber-500/10 dark:bg-amber-500/15",
    text: "text-amber-600 dark:text-amber-400",
    accentDot: "bg-amber-500",
    accentBorder: "hover:border-amber-500/50",
    accentGlow: "",
    tag: "Modern ES+",
    icon: <Code className="h-5 w-5" />,
  },

  // 2. Languages (Primary Pear)
  {
    id: "golang",
    label: "Go",
    category: "languages",
    categoryLabel: "Systems",
    bg: "bg-amber-500/10 dark:bg-amber-500/15",
    text: "text-amber-600 dark:text-amber-400",
    accentDot: "bg-amber-500",
    accentBorder: "hover:border-amber-500/50",
    accentGlow: "",
    tag: "Concurrent",
    icon: <Zap className="h-5 w-5" />,
  },
  {
    id: "python",
    label: "Python",
    category: "languages",
    categoryLabel: "Scripting",
    bg: "bg-amber-500/10 dark:bg-amber-500/15",
    text: "text-amber-600 dark:text-amber-400",
    accentDot: "bg-amber-500",
    accentBorder: "hover:border-amber-500/50",
    accentGlow: "",
    tag: "Algorithms",
    icon: <Braces className="h-5 w-5" />,
  },
  {
    id: "rust",
    label: "Rust",
    category: "languages",
    categoryLabel: "Memory Safe",
    bg: "bg-amber-500/10 dark:bg-amber-500/15",
    text: "text-amber-700 dark:text-amber-300",
    accentDot: "bg-amber-500",
    accentBorder: "hover:border-amber-500/50",
    accentGlow: "",
    tag: "Performance",
    icon: <Cpu className="h-5 w-5" />,
  },

  // 3. Backend & Data (Mint Green)
  {
    id: "node",
    label: "Node.js",
    category: "backend",
    categoryLabel: "Runtime",
    bg: "bg-emerald-500/10 dark:bg-emerald-500/15",
    text: "text-emerald-600 dark:text-emerald-400",
    accentDot: "bg-emerald-500",
    accentBorder: "hover:border-emerald-500/50",
    accentGlow: "",
    tag: "Backend",
    icon: <Server className="h-5 w-5" />,
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    category: "backend",
    categoryLabel: "Relational DB",
    bg: "bg-emerald-500/10 dark:bg-emerald-500/15",
    text: "text-emerald-600 dark:text-emerald-400",
    accentDot: "bg-emerald-500",
    accentBorder: "hover:border-emerald-500/50",
    accentGlow: "",
    tag: "SQL",
    icon: <Database className="h-5 w-5" />,
  },
  {
    id: "redis",
    label: "Redis",
    category: "backend",
    categoryLabel: "In-Memory DB",
    bg: "bg-emerald-500/10 dark:bg-emerald-500/15",
    text: "text-emerald-600 dark:text-emerald-400",
    accentDot: "bg-emerald-500",
    accentBorder: "hover:border-emerald-500/50",
    accentGlow: "",
    tag: "Cache / Queue",
    icon: <Layers className="h-5 w-5" />,
  },
  {
    id: "mongodb",
    label: "MongoDB",
    category: "backend",
    categoryLabel: "Document DB",
    bg: "bg-emerald-500/10 dark:bg-emerald-500/15",
    text: "text-emerald-600 dark:text-emerald-400",
    accentDot: "bg-emerald-500",
    accentBorder: "hover:border-emerald-500/50",
    accentGlow: "",
    tag: "NoSQL",
    icon: <HardDrive className="h-5 w-5" />,
  },

  // 4. Cloud & DevOps (Coral Pop)
  {
    id: "docker",
    label: "Docker",
    category: "devops",
    categoryLabel: "Containers",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "DevOps",
    icon: <Container className="h-5 w-5" />,
  },
  {
    id: "kubernetes",
    label: "Kubernetes",
    category: "devops",
    categoryLabel: "Orchestration",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "Clusters",
    icon: <Network className="h-5 w-5" />,
  },
  {
    id: "aws",
    label: "AWS",
    category: "devops",
    categoryLabel: "Cloud Platform",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "Cloud",
    icon: <Cloud className="h-5 w-5" />,
  },
  {
    id: "gcp",
    label: "Google Cloud",
    category: "devops",
    categoryLabel: "Cloud Platform",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "Infrastructure",
    icon: <Globe className="h-5 w-5" />,
  },
  {
    id: "linux",
    label: "Linux",
    category: "devops",
    categoryLabel: "OS Kernel",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "System",
    icon: <Terminal className="h-5 w-5" />,
  },
  {
    id: "ubuntu",
    label: "Ubuntu",
    category: "devops",
    categoryLabel: "Distribution",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "Server",
    icon: <Command className="h-5 w-5" />,
  },
  {
    id: "vercel",
    label: "Vercel",
    category: "devops",
    categoryLabel: "Edge & Deploy",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "Edge",
    icon: <Share2 className="h-5 w-5" />,
  },
  {
    id: "nginx",
    label: "Nginx",
    category: "devops",
    categoryLabel: "Reverse Proxy",
    bg: "bg-rose-500/10 dark:bg-rose-500/15",
    text: "text-rose-600 dark:text-rose-400",
    accentDot: "bg-rose-500",
    accentBorder: "hover:border-rose-500/50",
    accentGlow: "",
    tag: "Proxy",
    icon: <Shield className="h-5 w-5" />,
  },

  // 5. Tools, CI/CD & Security (Lilac Lavender)
  {
    id: "github",
    label: "GitHub",
    category: "tools",
    categoryLabel: "VCS & Git",
    bg: "bg-purple-500/10 dark:bg-purple-500/15",
    text: "text-purple-600 dark:text-purple-400",
    accentDot: "bg-purple-500",
    accentBorder: "hover:border-purple-500/50",
    accentGlow: "",
    tag: "Collaboration",
    icon: <GitBranch className="h-5 w-5" />,
  },
  {
    id: "actions",
    label: "GitHub Actions",
    category: "tools",
    categoryLabel: "CI / CD",
    bg: "bg-purple-500/10 dark:bg-purple-500/15",
    text: "text-purple-600 dark:text-purple-400",
    accentDot: "bg-purple-500",
    accentBorder: "hover:border-purple-500/50",
    accentGlow: "",
    tag: "Automations",
    icon: <Workflow className="h-5 w-5" />,
  },
  {
    id: "jenkins",
    label: "Jenkins",
    category: "tools",
    categoryLabel: "Pipelines",
    bg: "bg-purple-500/10 dark:bg-purple-500/15",
    text: "text-purple-600 dark:text-purple-400",
    accentDot: "bg-purple-500",
    accentBorder: "hover:border-purple-500/50",
    accentGlow: "",
    tag: "Pipelines",
    icon: <Activity className="h-5 w-5" />,
  },
  {
    id: "security",
    label: "Security",
    category: "tools",
    categoryLabel: "Auth & Cryptography",
    bg: "bg-purple-500/10 dark:bg-purple-500/15",
    text: "text-purple-600 dark:text-purple-400",
    accentDot: "bg-purple-500",
    accentBorder: "hover:border-purple-500/50",
    accentGlow: "",
    tag: "Security",
    icon: <Lock className="h-5 w-5" />,
  },
]
