import React from "react"
import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiPython,
  SiRust,
  SiC,
  SiCplusplus,
  SiNodedotjs,
  SiPostgresql,
  SiRedis,
  SiMongodb,
  SiDocker,
  SiKubernetes,
  SiGooglecloud,
  SiLinux,
  SiUbuntu,
  SiVercel,
  SiNginx,
  SiGithub,
  SiGithubactions,
  SiJenkins,
  SiBun,
  SiClaude,
  SiSupabase,
} from "react-icons/si"
import { TbBrandOpenai } from "react-icons/tb"
import { ShieldCheck } from "lucide-react"

// Custom SVG Icons for Antigravity, OpenCode, and MCP
export const AntigravityIcon = ({ className }: { className?: string }) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <circle cx="12" cy="12" r="3" fill="currentColor" />
    <ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(-30 12 12)" />
    <ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(30 12 12)" />
    <ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(90 12 12)" />
  </svg>
)

export const McpIcon = ({ className }: { className?: string }) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <path d="M4 12h4m8 0h4M12 4v4m0 8v4" />
    <circle cx="12" cy="12" r="3" />
    <rect x="2" y="10" width="4" height="4" rx="1" />
    <rect x="18" y="10" width="4" height="4" rx="1" />
    <rect x="10" y="2" width="4" height="4" rx="1" />
    <rect x="10" y="18" width="4" height="4" rx="1" />
  </svg>
)

export const OpenCodeIcon = ({ className }: { className?: string }) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <polyline points="4 17 10 11 4 5" />
    <line x1="12" y1="19" x2="20" y2="19" />
    <path d="M14 7h6a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-6" />
  </svg>
)

export type TechCategoryId =
  "all" | "frontend" | "languages" | "backend" | "devops" | "tools"

export interface TechCategory {
  id: TechCategoryId
  label: string
  dotColor: string
  accentColor: string
}

export const TECH_CATEGORIES: TechCategory[] = [
  {
    id: "all",
    label: "All Stack",
    dotColor: "bg-foreground/70",
    accentColor: "neutral",
  },
  {
    id: "frontend",
    label: "Frontend",
    dotColor: "bg-sky-500",
    accentColor: "cyan",
  },
  {
    id: "languages",
    label: "Languages",
    dotColor: "bg-amber-500",
    accentColor: "pear",
  },
  {
    id: "backend",
    label: "Backend & Data",
    dotColor: "bg-emerald-500",
    accentColor: "mint",
  },
  {
    id: "devops",
    label: "Cloud & DevOps",
    dotColor: "bg-rose-500",
    accentColor: "coral",
  },
  {
    id: "tools",
    label: "AI, Agents & Tools",
    dotColor: "bg-purple-500",
    accentColor: "lavender",
  },
]

export type TechItem = {
  id: string
  label: string
  bg: string
  text: string
  icon: React.ReactNode
  category: "frontend" | "languages" | "backend" | "devops" | "tools"
  categoryLabel: string
  accentDot: string
  accentBorder: string
  accentGlow: string
  tag: string
  brandColor: string
  brandLight: string
  textHover: string
  shadowColor: string
}

export const TECH_STACK_DATA: TechItem[] = [
  // 1. Frontend
  {
    id: "react",
    label: "React",
    category: "frontend",
    categoryLabel: "UI Library",
    bg: "bg-[#087EA4]/10",
    text: "text-[#087EA4] dark:text-[#61DAFB]",
    accentDot: "bg-[#087EA4]",
    accentBorder: "hover:border-[#087EA4]/50",
    accentGlow: "",
    tag: "Core",
    brandColor: "#087EA4",
    brandLight: "#DDF4FC",
    textHover: "#FFFFFF",
    shadowColor: "rgba(8, 126, 164, 0.45)",
    icon: <SiReact className="h-6 w-6" />,
  },
  {
    id: "nextjs",
    label: "Next.js",
    category: "frontend",
    categoryLabel: "Framework",
    bg: "bg-[#0070F3]/10",
    text: "text-[#0070F3]",
    accentDot: "bg-[#0070F3]",
    accentBorder: "hover:border-[#0070F3]/50",
    accentGlow: "",
    tag: "Production",
    brandColor: "#0070F3",
    brandLight: "#DCE9F8",
    textHover: "#FFFFFF",
    shadowColor: "rgba(0, 112, 243, 0.45)",
    icon: <SiNextdotjs className="h-6 w-6" />,
  },
  {
    id: "tailwind",
    label: "Tailwind CSS",
    category: "frontend",
    categoryLabel: "Styling",
    bg: "bg-[#06B6D4]/10",
    text: "text-[#06B6D4]",
    accentDot: "bg-[#06B6D4]",
    accentBorder: "hover:border-[#06B6D4]/50",
    accentGlow: "",
    tag: "Design",
    brandColor: "#06B6D4",
    brandLight: "#CFFAFE",
    textHover: "#FFFFFF",
    shadowColor: "rgba(6, 182, 212, 0.45)",
    icon: <SiTailwindcss className="h-6 w-6" />,
  },
  {
    id: "typescript",
    label: "TypeScript",
    category: "frontend",
    categoryLabel: "Typed JS",
    bg: "bg-[#3178C6]/10",
    text: "text-[#3178C6]",
    accentDot: "bg-[#3178C6]",
    accentBorder: "hover:border-[#3178C6]/50",
    accentGlow: "",
    tag: "Type-Safe",
    brandColor: "#3178C6",
    brandLight: "#DCE9F8",
    textHover: "#FFFFFF",
    shadowColor: "rgba(49, 120, 198, 0.45)",
    icon: <SiTypescript className="h-6 w-6" />,
  },
  {
    id: "javascript",
    label: "JavaScript",
    category: "frontend",
    categoryLabel: "Web Core",
    bg: "bg-[#F7DF1E]/10",
    text: "text-[#D97706] dark:text-[#F7DF1E]",
    accentDot: "bg-[#F7DF1E]",
    accentBorder: "hover:border-[#F7DF1E]/50",
    accentGlow: "",
    tag: "Modern ES+",
    brandColor: "#F7DF1E",
    brandLight: "#FEF9D2",
    textHover: "#451A03",
    shadowColor: "rgba(247, 223, 30, 0.45)",
    icon: <SiJavascript className="h-6 w-6" />,
  },

  // 2. Languages
  {
    id: "rust",
    label: "Rust",
    category: "languages",
    categoryLabel: "Memory Safe",
    bg: "bg-[#CE422B]/10",
    text: "text-[#CE422B]",
    accentDot: "bg-[#CE422B]",
    accentBorder: "hover:border-[#CE422B]/50",
    accentGlow: "",
    tag: "Performance",
    brandColor: "#CE422B",
    brandLight: "#FCE8DF",
    textHover: "#FFFFFF",
    shadowColor: "rgba(206, 66, 43, 0.45)",
    icon: <SiRust className="h-6 w-6" />,
  },
  {
    id: "cpp",
    label: "C++",
    category: "languages",
    categoryLabel: "Competitive & Systems",
    bg: "bg-[#00599C]/10",
    text: "text-[#00599C]",
    accentDot: "bg-[#00599C]",
    accentBorder: "hover:border-[#00599C]/50",
    accentGlow: "",
    tag: "High Perf",
    brandColor: "#00599C",
    brandLight: "#D6E8F7",
    textHover: "#FFFFFF",
    shadowColor: "rgba(0, 89, 156, 0.45)",
    icon: <SiCplusplus className="h-6 w-6" />,
  },
  {
    id: "c",
    label: "C",
    category: "languages",
    categoryLabel: "Low-Level Core",
    bg: "bg-[#00599C]/10",
    text: "text-[#00599C]",
    accentDot: "bg-[#00599C]",
    accentBorder: "hover:border-[#00599C]/50",
    accentGlow: "",
    tag: "Kernel / OS",
    brandColor: "#00599C",
    brandLight: "#D6E8F7",
    textHover: "#FFFFFF",
    shadowColor: "rgba(0, 89, 156, 0.45)",
    icon: <SiC className="h-6 w-6" />,
  },
  {
    id: "python",
    label: "Python",
    category: "languages",
    categoryLabel: "Scripting & DSA",
    bg: "bg-[#3776AB]/10",
    text: "text-[#3776AB]",
    accentDot: "bg-[#3776AB]",
    accentBorder: "hover:border-[#3776AB]/50",
    accentGlow: "",
    tag: "Algorithms",
    brandColor: "#3776AB",
    brandLight: "#D7E7F5",
    textHover: "#FFFFFF",
    shadowColor: "rgba(55, 118, 171, 0.45)",
    icon: <SiPython className="h-6 w-6" />,
  },

  // 3. Backend & Data
  {
    id: "node",
    label: "Node.js",
    category: "backend",
    categoryLabel: "Runtime",
    bg: "bg-[#5FA04E]/10",
    text: "text-[#5FA04E]",
    accentDot: "bg-[#5FA04E]",
    accentBorder: "hover:border-[#5FA04E]/50",
    accentGlow: "",
    tag: "Backend",
    brandColor: "#5FA04E",
    brandLight: "#D9EED3",
    textHover: "#FFFFFF",
    shadowColor: "rgba(95, 160, 78, 0.45)",
    icon: <SiNodedotjs className="h-6 w-6" />,
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    category: "backend",
    categoryLabel: "Relational DB",
    bg: "bg-[#336791]/10",
    text: "text-[#336791]",
    accentDot: "bg-[#336791]",
    accentBorder: "hover:border-[#336791]/50",
    accentGlow: "",
    tag: "SQL",
    brandColor: "#336791",
    brandLight: "#DCE7F2",
    textHover: "#FFFFFF",
    shadowColor: "rgba(51, 103, 145, 0.45)",
    icon: <SiPostgresql className="h-6 w-6" />,
  },
  {
    id: "redis",
    label: "Redis",
    category: "backend",
    categoryLabel: "In-Memory DB",
    bg: "bg-[#DC382D]/10",
    text: "text-[#DC382D]",
    accentDot: "bg-[#DC382D]",
    accentBorder: "hover:border-[#DC382D]/50",
    accentGlow: "",
    tag: "Cache / Queue",
    brandColor: "#DC382D",
    brandLight: "#FCE1DF",
    textHover: "#FFFFFF",
    shadowColor: "rgba(220, 56, 45, 0.45)",
    icon: <SiRedis className="h-6 w-6" />,
  },
  {
    id: "mongodb",
    label: "MongoDB",
    category: "backend",
    categoryLabel: "Document DB",
    bg: "bg-[#13AA52]/10",
    text: "text-[#13AA52]",
    accentDot: "bg-[#13AA52]",
    accentBorder: "hover:border-[#13AA52]/50",
    accentGlow: "",
    tag: "NoSQL",
    brandColor: "#13AA52",
    brandLight: "#D5F2E3",
    textHover: "#FFFFFF",
    shadowColor: "rgba(19, 170, 82, 0.45)",
    icon: <SiMongodb className="h-6 w-6" />,
  },
  {
    id: "supabase",
    label: "Supabase",
    category: "backend",
    categoryLabel: "Postgres BaaS",
    bg: "bg-[#3ECF8E]/10",
    text: "text-[#3ECF8E]",
    accentDot: "bg-[#3ECF8E]",
    accentBorder: "hover:border-[#3ECF8E]/50",
    accentGlow: "",
    tag: "Database",
    brandColor: "#3ECF8E",
    brandLight: "#D8F7EA",
    textHover: "#064E3B",
    shadowColor: "rgba(62, 207, 142, 0.45)",
    icon: <SiSupabase className="h-6 w-6" />,
  },
  {
    id: "bun",
    label: "Bun.js",
    category: "backend",
    categoryLabel: "Fast Runtime",
    bg: "bg-[#FBF0DF]/10",
    text: "text-[#D97706] dark:text-[#FBF0DF]",
    accentDot: "bg-[#E8A246]",
    accentBorder: "hover:border-[#E8A246]/50",
    accentGlow: "",
    tag: "Runtime",
    brandColor: "#E8A246",
    brandLight: "#FEF3C7",
    textHover: "#451A03",
    shadowColor: "rgba(232, 162, 70, 0.45)",
    icon: <SiBun className="h-6 w-6" />,
  },

  // 4. Cloud & DevOps
  {
    id: "docker",
    label: "Docker",
    category: "devops",
    categoryLabel: "Containers",
    bg: "bg-[#2496ED]/10",
    text: "text-[#2496ED]",
    accentDot: "bg-[#2496ED]",
    accentBorder: "hover:border-[#2496ED]/50",
    accentGlow: "",
    tag: "DevOps",
    brandColor: "#2496ED",
    brandLight: "#D3ECFC",
    textHover: "#FFFFFF",
    shadowColor: "rgba(36, 150, 237, 0.45)",
    icon: <SiDocker className="h-6 w-6" />,
  },
  {
    id: "kubernetes",
    label: "Kubernetes",
    category: "devops",
    categoryLabel: "Orchestration",
    bg: "bg-[#326CE5]/10",
    text: "text-[#326CE5]",
    accentDot: "bg-[#326CE5]",
    accentBorder: "hover:border-[#326CE5]/50",
    accentGlow: "",
    tag: "Clusters",
    brandColor: "#326CE5",
    brandLight: "#D6E2FA",
    textHover: "#FFFFFF",
    shadowColor: "rgba(50, 108, 229, 0.45)",
    icon: <SiKubernetes className="h-6 w-6" />,
  },
  {
    id: "gcp",
    label: "Google Cloud",
    category: "devops",
    categoryLabel: "Cloud Platform",
    bg: "bg-[#4285F4]/10",
    text: "text-[#4285F4]",
    accentDot: "bg-[#4285F4]",
    accentBorder: "hover:border-[#4285F4]/50",
    accentGlow: "",
    tag: "Infrastructure",
    brandColor: "#4285F4",
    brandLight: "#D9E7FD",
    textHover: "#FFFFFF",
    shadowColor: "rgba(66, 133, 244, 0.45)",
    icon: <SiGooglecloud className="h-6 w-6" />,
  },
  {
    id: "linux",
    label: "Linux",
    category: "devops",
    categoryLabel: "OS Kernel",
    bg: "bg-[#FCC624]/10",
    text: "text-[#D97706] dark:text-[#FCC624]",
    accentDot: "bg-[#FCC624]",
    accentBorder: "hover:border-[#FCC624]/50",
    accentGlow: "",
    tag: "System",
    brandColor: "#FCC624",
    brandLight: "#FEF3D3",
    textHover: "#451A03",
    shadowColor: "rgba(252, 198, 36, 0.45)",
    icon: <SiLinux className="h-6 w-6" />,
  },
  {
    id: "ubuntu",
    label: "Ubuntu",
    category: "devops",
    categoryLabel: "Distribution",
    bg: "bg-[#E95420]/10",
    text: "text-[#E95420]",
    accentDot: "bg-[#E95420]",
    accentBorder: "hover:border-[#E95420]/50",
    accentGlow: "",
    tag: "Server",
    brandColor: "#E95420",
    brandLight: "#FCDCD2",
    textHover: "#FFFFFF",
    shadowColor: "rgba(233, 84, 32, 0.45)",
    icon: <SiUbuntu className="h-6 w-6" />,
  },
  {
    id: "vercel",
    label: "Vercel",
    category: "devops",
    categoryLabel: "Edge & Deploy",
    bg: "bg-[#0070F3]/10",
    text: "text-[#0070F3]",
    accentDot: "bg-[#0070F3]",
    accentBorder: "hover:border-[#0070F3]/50",
    accentGlow: "",
    tag: "Edge",
    brandColor: "#0070F3",
    brandLight: "#DCE9F8",
    textHover: "#FFFFFF",
    shadowColor: "rgba(0, 112, 243, 0.45)",
    icon: <SiVercel className="h-6 w-6" />,
  },
  {
    id: "nginx",
    label: "Nginx",
    category: "devops",
    categoryLabel: "Reverse Proxy",
    bg: "bg-[#009639]/10",
    text: "text-[#009639]",
    accentDot: "bg-[#009639]",
    accentBorder: "hover:border-[#009639]/50",
    accentGlow: "",
    tag: "Proxy",
    brandColor: "#009639",
    brandLight: "#CCF0DA",
    textHover: "#FFFFFF",
    shadowColor: "rgba(0, 150, 57, 0.45)",
    icon: <SiNginx className="h-6 w-6" />,
  },

  // 5. Tools, AI & Agent Ecosystem
  {
    id: "claude",
    label: "Claude AI",
    category: "tools",
    categoryLabel: "Anthropic LLM",
    bg: "bg-[#D97757]/10",
    text: "text-[#D97757]",
    accentDot: "bg-[#D97757]",
    accentBorder: "hover:border-[#D97757]/50",
    accentGlow: "",
    tag: "AI Model",
    brandColor: "#D97757",
    brandLight: "#FBEAE4",
    textHover: "#FFFFFF",
    shadowColor: "rgba(217, 119, 87, 0.45)",
    icon: <SiClaude className="h-6 w-6" />,
  },
  {
    id: "chatgpt",
    label: "ChatGPT",
    category: "tools",
    categoryLabel: "OpenAI AI",
    bg: "bg-[#10A37F]/10",
    text: "text-[#10A37F]",
    accentDot: "bg-[#10A37F]",
    accentBorder: "hover:border-[#10A37F]/50",
    accentGlow: "",
    tag: "AI Model",
    brandColor: "#10A37F",
    brandLight: "#D1F2E8",
    textHover: "#FFFFFF",
    shadowColor: "rgba(16, 163, 127, 0.45)",
    icon: <TbBrandOpenai className="h-6 w-6" />,
  },
  {
    id: "codex",
    label: "Codex",
    category: "tools",
    categoryLabel: "AI Synthesis",
    bg: "bg-[#0284C7]/10",
    text: "text-[#0284C7]",
    accentDot: "bg-[#0284C7]",
    accentBorder: "hover:border-[#0284C7]/50",
    accentGlow: "",
    tag: "Code AI",
    brandColor: "#0284C7",
    brandLight: "#E0F2FE",
    textHover: "#FFFFFF",
    shadowColor: "rgba(2, 132, 199, 0.45)",
    icon: <TbBrandOpenai className="h-6 w-6" />,
  },
  {
    id: "opencode",
    label: "OpenCode",
    category: "tools",
    categoryLabel: "AI Terminal",
    bg: "bg-[#10B981]/10",
    text: "text-[#10B981]",
    accentDot: "bg-[#10B981]",
    accentBorder: "hover:border-[#10B981]/50",
    accentGlow: "",
    tag: "Open Source",
    brandColor: "#10B981",
    brandLight: "#D1FAE5",
    textHover: "#FFFFFF",
    shadowColor: "rgba(16, 185, 129, 0.45)",
    icon: <OpenCodeIcon className="h-6 w-6" />,
  },
  {
    id: "antigravity",
    label: "Antigravity",
    category: "tools",
    categoryLabel: "Agentic IDE",
    bg: "bg-[#8B5CF6]/10",
    text: "text-[#8B5CF6]",
    accentDot: "bg-[#8B5CF6]",
    accentBorder: "hover:border-[#8B5CF6]/50",
    accentGlow: "",
    tag: "AI Agents",
    brandColor: "#8B5CF6",
    brandLight: "#EDE9FE",
    textHover: "#FFFFFF",
    shadowColor: "rgba(139, 92, 246, 0.45)",
    icon: <AntigravityIcon className="h-6 w-6" />,
  },
  {
    id: "mcp",
    label: "MCP",
    category: "tools",
    categoryLabel: "Model Protocol",
    bg: "bg-[#F97316]/10",
    text: "text-[#F97316]",
    accentDot: "bg-[#F97316]",
    accentBorder: "hover:border-[#F97316]/50",
    accentGlow: "",
    tag: "Protocol",
    brandColor: "#F97316",
    brandLight: "#FFEDD5",
    textHover: "#FFFFFF",
    shadowColor: "rgba(249, 115, 22, 0.45)",
    icon: <McpIcon className="h-6 w-6" />,
  },
  {
    id: "github",
    label: "GitHub",
    category: "tools",
    categoryLabel: "VCS & Git",
    bg: "bg-[#6E5494]/10",
    text: "text-[#6E5494] dark:text-[#A78BFA]",
    accentDot: "bg-[#6E5494]",
    accentBorder: "hover:border-[#6E5494]/50",
    accentGlow: "",
    tag: "Collaboration",
    brandColor: "#6E5494",
    brandLight: "#EDE9FE",
    textHover: "#FFFFFF",
    shadowColor: "rgba(110, 84, 148, 0.45)",
    icon: <SiGithub className="h-6 w-6" />,
  },
  {
    id: "actions",
    label: "GitHub Actions",
    category: "tools",
    categoryLabel: "CI / CD",
    bg: "bg-[#2088FF]/10",
    text: "text-[#2088FF]",
    accentDot: "bg-[#2088FF]",
    accentBorder: "hover:border-[#2088FF]/50",
    accentGlow: "",
    tag: "Automations",
    brandColor: "#2088FF",
    brandLight: "#D2E7FF",
    textHover: "#FFFFFF",
    shadowColor: "rgba(32, 136, 255, 0.45)",
    icon: <SiGithubactions className="h-6 w-6" />,
  },
  {
    id: "jenkins",
    label: "Jenkins",
    category: "tools",
    categoryLabel: "Pipelines",
    bg: "bg-[#D33833]/10",
    text: "text-[#D33833]",
    accentDot: "bg-[#D33833]",
    accentBorder: "hover:border-[#D33833]/50",
    accentGlow: "",
    tag: "Pipelines",
    brandColor: "#D33833",
    brandLight: "#F9D7D6",
    textHover: "#FFFFFF",
    shadowColor: "rgba(211, 56, 51, 0.45)",
    icon: <SiJenkins className="h-6 w-6" />,
  },
  {
    id: "security",
    label: "Security",
    category: "tools",
    categoryLabel: "Auth & Crypto",
    bg: "bg-[#9333EA]/10",
    text: "text-[#9333EA]",
    accentDot: "bg-[#9333EA]",
    accentBorder: "hover:border-[#9333EA]/50",
    accentGlow: "",
    tag: "Security",
    brandColor: "#9333EA",
    brandLight: "#F3E8FF",
    textHover: "#FFFFFF",
    shadowColor: "rgba(147, 51, 234, 0.45)",
    icon: <ShieldCheck className="h-6 w-6" />,
  },
]
