/** @jsxImportSource react */
import {
  Activity,
  Braces,
  Cloud,
  Code,
  Command,
  Container,
  Cpu,
  Database,
  GitBranch,
  Globe,
  HardDrive,
  Layout,
  Layers,
  Network,
  Server,
  Shield,
  Share2,
  Terminal,
  Workflow,
  Rocket,
  Lock,
  Zap,
} from "lucide-react"

export type TechItem = {
  id: string
  label: string
  bg: string
  text: string
  icon: React.ReactNode
}

export const TECH_STACK_DATA: TechItem[] = [
  {
    id: "react",
    label: "React",
    bg: "bg-sky-500/10",
    text: "text-sky-700 dark:text-sky-300",
    icon: <Code size={18} />,
  },
  {
    id: "nextjs",
    label: "Next.js",
    bg: "bg-zinc-500/10",
    text: "text-zinc-800 dark:text-zinc-200",
    icon: <Rocket size={18} />,
  },
  {
    id: "tailwind",
    label: "Tailwind",
    bg: "bg-cyan-500/10",
    text: "text-cyan-700 dark:text-cyan-300",
    icon: <Layout size={18} />,
  },
  {
    id: "typescript",
    label: "TypeScript",
    bg: "bg-blue-600/10",
    text: "text-blue-700 dark:text-blue-300",
    icon: <Code size={18} />,
  },
  {
    id: "javascript",
    label: "JavaScript",
    bg: "bg-yellow-500/10",
    text: "text-yellow-700 dark:text-yellow-300",
    icon: <Code size={18} />,
  },
  {
    id: "node",
    label: "Node.js",
    bg: "bg-green-600/10",
    text: "text-green-700 dark:text-green-300",
    icon: <Server size={18} />,
  },
  {
    id: "python",
    label: "Python",
    bg: "bg-blue-500/10",
    text: "text-blue-700 dark:text-blue-300",
    icon: <Braces size={18} />,
  },
  {
    id: "golang",
    label: "Go",
    bg: "bg-cyan-400/10",
    text: "text-cyan-700 dark:text-cyan-300",
    icon: <Zap size={18} />,
  },
  {
    id: "rust",
    label: "Rust",
    bg: "bg-orange-500/10",
    text: "text-orange-700 dark:text-orange-300",
    icon: <Cpu size={18} />,
  },
  {
    id: "linux",
    label: "Linux",
    bg: "bg-amber-500/10",
    text: "text-amber-700 dark:text-amber-300",
    icon: <Terminal size={18} />,
  },
  {
    id: "ubuntu",
    label: "Ubuntu",
    bg: "bg-orange-600/10",
    text: "text-orange-700 dark:text-orange-300",
    icon: <Command size={18} />,
  },
  {
    id: "docker",
    label: "Docker",
    bg: "bg-blue-500/10",
    text: "text-blue-700 dark:text-blue-300",
    icon: <Container size={18} />,
  },
  {
    id: "kubernetes",
    label: "Kubernetes",
    bg: "bg-indigo-500/10",
    text: "text-indigo-700 dark:text-indigo-300",
    icon: <Network size={18} />,
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    bg: "bg-blue-700/10",
    text: "text-blue-800 dark:text-blue-300",
    icon: <Database size={18} />,
  },
  {
    id: "mongodb",
    label: "MongoDB",
    bg: "bg-green-500/10",
    text: "text-green-700 dark:text-green-300",
    icon: <HardDrive size={18} />,
  },
  {
    id: "redis",
    label: "Redis",
    bg: "bg-red-500/10",
    text: "text-red-700 dark:text-red-300",
    icon: <Layers size={18} />,
  },
  {
    id: "aws",
    label: "AWS",
    bg: "bg-orange-400/10",
    text: "text-orange-700 dark:text-orange-300",
    icon: <Cloud size={18} />,
  },
  {
    id: "gcp",
    label: "Google Cloud",
    bg: "bg-sky-500/10",
    text: "text-sky-700 dark:text-sky-300",
    icon: <Globe size={18} />,
  },
  {
    id: "vercel",
    label: "Vercel",
    bg: "bg-zinc-500/10",
    text: "text-zinc-800 dark:text-zinc-200",
    icon: <Share2 size={18} />,
  },
  {
    id: "nginx",
    label: "Nginx",
    bg: "bg-green-600/10",
    text: "text-green-700 dark:text-green-300",
    icon: <Shield size={18} />,
  },
  {
    id: "github",
    label: "GitHub",
    bg: "bg-slate-500/10",
    text: "text-slate-700 dark:text-slate-300",
    icon: <GitBranch size={18} />,
  },
  {
    id: "actions",
    label: "GitHub Actions",
    bg: "bg-blue-500/10",
    text: "text-blue-700 dark:text-blue-300",
    icon: <Workflow size={18} />,
  },
  {
    id: "jenkins",
    label: "Jenkins",
    bg: "bg-red-500/10",
    text: "text-red-700 dark:text-red-300",
    icon: <Activity size={18} />,
  },
  {
    id: "security",
    label: "Security",
    bg: "bg-purple-500/10",
    text: "text-purple-700 dark:text-purple-300",
    icon: <Lock size={18} />,
  },
]
